setwd("/Users/elijahedmondson/Desktop/R/QTL/WD/Background.Plots")

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.BHGT.Rdata")
jpeg('Harderian Gland Tumors, Bilateral (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Harderian Gland Tumors, Bilateral (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.CPT.Rdata")
jpeg('Choroid Plexus Tumor (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Choroid Plexus Tumor (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.Dpolyp.Rdata")
jpeg('Duodenal Polyp (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Duodenal Polyp (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.Ectoderm.Rdata")
jpeg('Ectoderm Derived Tumor (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Ectoderm Derived Tumor (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.Endoderm.Rdata")
jpeg('Endoderm Derived Tumor (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Endoderm Derived Tumor (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.EndoPolyp.Rdata")
jpeg('Endometrial Stromal Polyp (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Endometrial Stromal Polyp (Uirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.Ependymoma.Rdata")
jpeg('Ependymoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Ependymoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.Epidermal.Rdata")
jpeg('Epidermis Derived Tumors (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Epidermis Derived Tumors (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.FSA.Rdata")
jpeg('Fibrosarcoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Fibrosarcoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.GastSCC.Rdata")
jpeg('Gastric Squamous Cell Carcinoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Gastric Squamous Cell Carcinoma (Unirradiated)")
dev.off()

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.GCT.Rdata")
jpeg('Ovarian Granulosa Cell Tumor (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Ovarian Granulosa Cell Tumor (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.HCAd.Rdata")
jpeg('Hepatocellular Adenoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Hepatocellular Adenoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.HCC.Rdata")
jpeg('Hepatocellular Carcinoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Hepatocellular Carcinoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.Hemangioma.Rdata")
jpeg('Hemangioma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Hemangioma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.Hepatoblastoma.Rdata")
jpeg('Hepatoblastoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Hepatoblastoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.HGAca.Rdata")
jpeg('Harderian Gland Adenocarcinoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Harderian Gland Adenocarcinoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.HGAd.Rdata")
jpeg('Harderian Gland Adenoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Harderian Gland Adenoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.HS.Rdata")
jpeg('Histiocytic Sarcoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Histiocytic Sarcoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.HSA.Rdata")
jpeg('Hemangiosarcoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Hemangiosarcoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.IntestinalACA.Rdata")
jpeg('Intestinal Adenocarcinoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Intestinal Adenocarcinoma (Unirradiated)")
dev.off()

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.IntestinalNeo.Rdata")
jpeg('Intestinal Neoplasm (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Intestinal Neoplasm (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.Intracranial.Rdata")
jpeg('Intracranial Neoplasm (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Intracranial Neoplasm (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.Islet.Rdata")
jpeg('Pancreatic Islet Cell Tumor (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Pancreatic Islet Cell Tumor (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.Leiomyosarcoma.Rdata")
jpeg('Leiomyosarcoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Leiomyosarcoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.LSA.Rdata")
jpeg('Lymphoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Lymphoma (Unirradiated)")
dev.off()

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.MalMammary.Rdata")
jpeg('Malignant Mammary Tumor (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Malignant Mammary Tumor (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.MalOvarian.Rdata")
jpeg('Malignant Ovarian Tumor (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Malignant Ovarian Tumor (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.MammAdenoacanthoma.Rdata")
jpeg('Mammary Adenoacanthoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Mammary Adenoacanthoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.MammAdenocarcinoma.Rdata")
jpeg('Mammary Adenocarcinoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Mammary Adenocarcinoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.Meningioma.Rdata")
jpeg('Meningioma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Meningioma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.Mesoderm.Rdata")
jpeg('Mesoderm Derived Tumor (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Mesoderm Derived Tumor (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.Mesothelioma.Rdata")
jpeg('Mesothelioma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Mesothelioma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.Met.Rdata")
jpeg('Metastatic Disease (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Metastatic Disease (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.Myeloid.Leukemia.Rdata")
jpeg('Myeloid Leukemia (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Myeloid Leukemia (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.Myxosarcoma.Rdata")
jpeg('Myxosarcoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Myxosarcoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.NN.Rdata")
jpeg('Non-neoplastic (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Non-neoplastic (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.Odontogenic.Rdata")
jpeg('Odotogenic Tumors (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Odontogenic Tumors (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.OSA.Rdata")
jpeg('Osteosarcoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Osteosarcoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.Osteoma.Rdata")
jpeg('Osteoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Osteoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.OvarianCarc.Rdata")
jpeg('Ovarian Carcinoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Ovarian Carcinoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.Pheo.Rdata")
jpeg('Pheochromocytoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Pheochromocytoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.PitAd.Rdata")
jpeg('Pituitary Adenoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Pituitary Adenoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.PulAd.Rdata")
jpeg('Pulmonary Adenoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Pulmonary Adenoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.PulAdenoma.Rdata")
jpeg('Pulmonary Adenoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Pulmonary Adenoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.PulMetastasis.Rdata")
jpeg('Pulmonary Metastases (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Pulmonary Metastases (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.PulmonaryAdenocarcinoma.Rdata")
jpeg('Pulmonary Adenocarcinoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Pulmonary Adenocarcinoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.PulSarcomatoidCarc.Rdata")
jpeg('Pulmonary Sarcomatoid Carcinoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Pulmonary Sarcomatoid Carcinoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.RCC.Rdata")
jpeg('Renal Cell Carcinoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Renal Cell Carcinoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.RhSA.Rdata")
jpeg('Rhabdomyosarcoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Rhabdomyosarcoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.STS.Rdata")
jpeg('Soft Tissue Sarcoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Soft Tissue Sarcoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.ThyroidAd.Rdata")
jpeg('Thyroid Follicular Adenoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Thyroid Follicular Adenoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.ThyroidCarc.Rdata")
jpeg('Thyroid Follicular Carcinoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Thyroid Follicular Carcinoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.TubulostromalACA.Rdata")
jpeg('Ovarian Tubulostroma Adenocarcinoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Ovarian Tubulostroma Adenocarcinoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.TubulostromalAd.Rdata")
jpeg('Ovarian Tubulostromal Adenoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Ovarian Tubulostromal Adenoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.UndiffSarc.Rdata")
jpeg('Undifferentiated Sarcoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Undifferentiated Sarcoma (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.UnilHarderian.Rdata")
jpeg('Harderian Gland Tumor, Unilateral (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Harderian Gland Tumor, Unilateral (Unirradiated)")
dev.off()
rm(AM.qtl)

load(file ="/Users/elijahedmondson/Desktop/R/QTL/WD/Background/AMQTL.UterineStromalSarc.Rdata")
jpeg('Uterine Stromal Sarcoma (Unirradiated)', width = 1600, height = 800, res = 80)
DOQTL:::plot.scanone.assoc(AM.qtl, bin.size = 100, main = "Uterine Stromal Sarcoma (Unirradiated)")
dev.off()
rm(AM.qtl)