library(BSgenome.Mmusculus.UCSC.mm10)
library(doParallel)
library(VariantAnnotation)
library(GenomicRanges)
library(regress)
library(MASS)
library(DOQTL)
library(lmtest)
library(HZE)
options(stringsAsFactors = F)
load(file = "~/Desktop/R/QTL/WD/GRSD.Rdata")
setwd("~/Desktop/files")
outdir = "~/Desktop/files"

GRSD.assoc(pheno = All.irr, pheno.col = "PulACA", probs, K, addcovar = Allirr.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Allirr", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = All.irr, pheno.col = "HCC", probs, K, addcovar = Allirr.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Allirr", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = All.irr, pheno.col = "HSA", probs, K, addcovar = Allirr.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Allirr", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = All.irr, pheno.col = "HS", probs, K, addcovar = Allirr.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Allirr", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = All.irr, pheno.col = "MammACA", probs, K, addcovar = Allirr.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Allirr", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = All.irr, pheno.col = "GCT", probs, K, addcovar = Allirr.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Allirr", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = All.irr, pheno.col = "GCT", probs, K, addcovar = Allirr.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Allirr", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = All.irr, pheno.col = "Thyroid", probs, K, addcovar = Allirr.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Allirr", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = All.irr, pheno.col = "ThyroidAD", probs, K, addcovar = Allirr.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Allirr", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = All.irr, pheno.col = "STS", probs, K, addcovar = Allirr.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Allirr", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = All.irr, pheno.col = "AML", probs, K, addcovar = Allirr.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Allirr", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = All.irr, pheno.col = "HardACA", probs, K, addcovar = Allirr.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Allirr", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = All.irr, pheno.col = "Harderian", probs, K, addcovar = Allirr.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Allirr", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = All.irr, pheno.col = "HardAD", probs, K, addcovar = Allirr.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Allirr", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = All.irr, pheno.col = "LSA.BLL", probs, K, addcovar = Allirr.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Allirr", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = All.irr, pheno.col = "LSA.Bmerge", probs, K, addcovar = Allirr.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Allirr", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = All.irr, pheno.col = "LSA.DLBCL", probs, K, addcovar = Allirr.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Allirr", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = All.irr, pheno.col = "LSA.FBL", probs, K, addcovar = Allirr.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Allirr", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = All.irr, pheno.col = "LSA.PreT", probs, K, addcovar = Allirr.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Allirr", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = All.irr, pheno.col = "OSA", probs, K, addcovar = Allirr.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Allirr", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")

GRSD.assoc(pheno = All.irr, pheno.col = "Amyloid", probs, K, addcovar = Allirr.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Allirr", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = HZE, pheno.col = "Amyloid", probs, K, addcovar = HZE.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "HZE", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = Gamma, pheno.col = "Amyloid", probs, K, addcovar = Gamma.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Gamma", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = Un, pheno.col = "Amyloid", probs, K, addcovar = Un.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Unirradiated", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")

GRSD.assoc(pheno = All.irr, pheno.col = "NN", probs, K, addcovar = Allirr.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Allirr", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = HZE, pheno.col = "NN", probs, K, addcovar = HZE.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "HZE", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = Gamma, pheno.col = "NN", probs, K, addcovar = Gamma.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Gamma", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = Un, pheno.col = "NN", probs, K, addcovar = Un.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Unirradiated", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")

GRSD.assoc(pheno = All.irr, pheno.col = "ectoderm", probs, K, addcovar = Allirr.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Allirr", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = HZE, pheno.col = "ectoderm", probs, K, addcovar = HZE.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "HZE", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = Gamma, pheno.col = "ectoderm", probs, K, addcovar = Gamma.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Gamma", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = Un, pheno.col = "ectoderm", probs, K, addcovar = Un.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Unirradiated", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")

GRSD.assoc(pheno = All.irr, pheno.col = "endoderm", probs, K, addcovar = Allirr.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Allirr", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = HZE, pheno.col = "endoderm", probs, K, addcovar = HZE.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "HZE", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = Gamma, pheno.col = "endoderm", probs, K, addcovar = Gamma.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Gamma", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = Un, pheno.col = "endoderm", probs, K, addcovar = Un.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Unirradiated", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")

GRSD.assoc(pheno = All.irr, pheno.col = "mesoderm", probs, K, addcovar = Allirr.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Allirr", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = HZE, pheno.col = "mesoderm", probs, K, addcovar = HZE.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "HZE", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = Gamma, pheno.col = "mesoderm", probs, K, addcovar = Gamma.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Gamma", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
GRSD.assoc(pheno = Un, pheno.col = "mesoderm", probs, K, addcovar = Un.add, markers, snp.file = "snp.file", outdir = "~/Desktop/files", tx = "Unirradiated", sanger.dir = "~/Desktop/R/QTL/WD/HS.sanger.files/")
